language: node_js
node_js:
  - 12
  
install:
- npm install newman

before_script:
- node --version
- npm --version
- node_modules/npm/.bin/newman --version

script:

- newman run APIs_Automatizacion/API_Blacklist.postman_collection.json
# pruebas
